spring:
  application:
    name: demoQrcode
  
  # --- DATABASE CONFIG ---
  datasource:
    url: jdbc:postgresql://localhost:5432/qr_demo_db
    username: code_qr_user
    password: demo_pass_ChangeMe
    hikari:
      maximum-pool-size: 10
  
  # --- JPA & HIBERNATE ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # --- H2 CONSOLE (dev uniquement) ---
  h2:
    console:
      enabled: true
  
  # --- DISABLE AUTORESTART ---
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  
  main:
    web-application-type: servlet

# --- JWT CONFIG ---
jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890}
  expiration: 3600000

# --- SERVER ---
server:
  port: 8080

logging:
  level:
    root: INFO
  file:
    name: logs/demoqrcode.log

# Configuration CORS pour le frontend
app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000,http://localhost:4200,http://localhost:8080
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,Origin,Access-Control-Request-Method,Access-Control-Request-Headers,X-Test-Type,X-Test-Index
    exposed-headers: Authorization,Content-Type,X-Test-Type,X-Test-Index
    allow-credentials: true
    max-age: 3600

# --- UEMOA QR CODE CONFIGURATION ---
uemoa:
  qr:
    # Configuration par défaut pour l'UEMOA
    country-code: CI
    currency: XOF
    merchant-category-code: 0000
    merchant-name: "LIQUIDATION APP"
    merchant-city: "Abidjan"
    merchant-postal-code: "225"
    merchant-country: "CI"
    
    # Configuration du système de paiement
    payment-system:
      identifier: "int.bceao.pi"
      name: "BCEAO Payment Interface"
    
    # Configuration des montants par défaut
    default-amount: 100
    min-amount: 1
    max-amount: 999999
    
    # Configuration des QR codes
    qr:
      size: 300
      format: "PNG"
      error-correction: "M"
      
    # Configuration des tests
    test:
      enabled: true
      merchant-id: "test-123"
      terminal-id: "test-terminal"
